name: 'Hello Wrold'
description: 'Greet someone and record the time'
input: 
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  outputs:
    time:
      description: 'The time we greeted your'
  runs:
    using: 'docker'
    images: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}
